#!/usr/bin/env node
/**
 * 根据 js/quick-actions.js + package.json 的 addonType，生成 ribbon.xml。
 *
 * 思路：
 *   - 读取当前 addonType（wps/et/wpp/pdf）
 *   - 加载 quick-actions.js 拿到该宿主的 QUICK_ACTIONS、CATEGORY_LABELS、CATEGORY_ICON
 *   - 按分类生成 <group label="写作"><button .../></group> 这样的 ribbon 结构
 *   - 每个 button 的 image 用对应分类的线性图标
 *
 * 用法：
 *   node tools/gen-ribbon.js          # 按当前 addonType 生成
 *   node tools/gen-ribbon.js wps      # 强制指定宿主
 */

const fs = require("fs");
const path = require("path");

const root = path.resolve(__dirname, "..");
const generatedRibbonCallbacksPath = path.resolve(root, "js", "ribbon-callbacks.generated.js");

function loadQuickActions() {
  const code = fs.readFileSync(path.resolve(root, "js/quick-actions.js"), "utf8");
  const win = {};
  new Function("window", code)(win);
  if (!win.WpsAiQuickActions) throw new Error("quick-actions.js 没有挂到 window.WpsAiQuickActions");
  return win.WpsAiQuickActions;
}

function readAddonType() {
  const cliArg = process.argv[2];
  if (cliArg && ["wps", "et", "wpp", "pdf"].includes(cliArg)) return cliArg;
  const pkg = JSON.parse(fs.readFileSync(path.resolve(root, "package.json"), "utf8"));
  return pkg.addonType || "wps";
}

function escapeXml(s) {
  return String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;").replace(/'/g, "&apos;");
}

function callbackSuffixFromId(id) {
  return String(id || "")
    .replace(/[^A-Za-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "")
    || "unknown";
}

function actionCallbackName(id) {
  return `OnAction_${callbackSuffixFromId(id)}`;
}

function imageCallbackName(id) {
  return `GetImage_${callbackSuffixFromId(id)}`;
}

function pngIconPath(iconPath) {
  return String(iconPath || "images/ai.svg").replace(/\.svg(?:$|\?)/, (match) => match.replace(".svg", ".png"));
}

function iconPathForButton(host, qa, id, action, category) {
  if (id === "openWpsAiPane") return "images/ai.png";
  if (id === "lingxiStyleBtn") return "images/icons/palette.png";
  if (id === "lingxiUnifyBtn") return "images/icons/wand.png";
  if (id === "lingxiDeAiBtn") return "images/icons/scrub.png";
  const resolvedCategory = category || action?.category || "";
  return pngIconPath(qa.CATEGORY_ICON?.[resolvedCategory]);
}

function buttonAttrs({ id, label, size, iconPath, visible = false }) {
  const attrs = [
    `id="${escapeXml(id)}"`,
    `label="${escapeXml(label)}"`,
    `size="${escapeXml(size)}"`,
    `image="${escapeXml(iconPath)}"`,
    `onAction="${actionCallbackName(id)}"`,
    `getImage="${imageCallbackName(id)}"`
  ];
  if (visible) attrs.push('getVisible="OnGetVisible"');
  attrs.push('getEnabled="OnGetEnabled"');
  return attrs.join(" ");
}

function buildRibbonCallbackScript(host, qa) {
  const ids = ["openWpsAiPane"];
  if (host === "wpp") ids.push("lingxiStyleBtn", "lingxiUnifyBtn", "lingxiDeAiBtn");
  qa.getRibbonGroups(host).forEach((group) => {
    group.actions.forEach((act) => ids.push(`quick.${host}.${act.key}`));
  });

  const lines = [];
  lines.push("// Auto-generated by tools/gen-ribbon.js. Do not edit manually.");
  lines.push("(function registerGeneratedRibbonCallbacks(global) {");
  lines.push('  "use strict";');
  lines.push("  const bindAction = global.__lingxiBindRibbonAction;");
  lines.push("  const bindImage = global.__lingxiBindRibbonImage;");
  lines.push("  const trace = global.__lingxiTraceStatic;");
  lines.push(`  if (typeof trace === "function") trace("generated.ribbonCallbacks.start", ${JSON.stringify({ host, count: ids.length })});`);
  ids.forEach((id) => {
    lines.push(`  if (typeof bindAction === "function") bindAction(${JSON.stringify(actionCallbackName(id))}, ${JSON.stringify(id)});`);
    lines.push(`  if (typeof bindImage === "function") bindImage(${JSON.stringify(imageCallbackName(id))}, ${JSON.stringify(id)});`);
  });
  lines.push(`  if (typeof trace === "function") trace("generated.ribbonCallbacks.done", ${JSON.stringify({ host, ids })});`);
  lines.push("})(window);");
  lines.push("");
  return lines.join("\n");
}

function buildRibbon(host, qa) {
  const groups = qa.getRibbonGroups(host);
  const lines = [];
  lines.push('<?xml version="1.0" encoding="UTF-8"?>');
  lines.push('<customUI xmlns="http://schemas.microsoft.com/office/2006/01/customui" onLoad="OnAddinLoad">');
  lines.push('  <ribbon startFromScratch="false">');
  lines.push('    <tabs>');
  // 所有四个宿主都把灵犀AI 插在"开始"前面。WPS Office 主程序里 wps/et/wpp/PDF 阅读模式
  // 的"开始"标签 mso id 统一是 TabHome（早期排查 PDF 不显示其实是 serve-permanent
  // 的 /pdf/* 路由 404 导致的，跟 anchor 无关）。
  lines.push('      <tab id="wpsAiTab" label="灵犀AI" 	insertBeforeMso="TabHome">');

  // 主入口 group：「打开灵犀AI」 + PPT 宿主额外的「PPT 风格」「统一风格」按钮
  lines.push('        <group id="lingxiCore" label="灵犀AI">');
  lines.push(`          <button ${buttonAttrs({ id: "openWpsAiPane", label: "打开灵犀AI", size: "large", iconPath: iconPathForButton(host, qa, "openWpsAiPane"), visible: true })}/>`);
  if (host === "wpp") {
    lines.push(`          <button ${buttonAttrs({ id: "lingxiStyleBtn", label: "PPT 风格", size: "large", iconPath: iconPathForButton(host, qa, "lingxiStyleBtn") })}/>`);
    lines.push(`          <button ${buttonAttrs({ id: "lingxiUnifyBtn", label: "统一风格", size: "large", iconPath: iconPathForButton(host, qa, "lingxiUnifyBtn") })}/>`);
    lines.push(`          <button ${buttonAttrs({ id: "lingxiDeAiBtn", label: "去 AI 味", size: "large", iconPath: iconPathForButton(host, qa, "lingxiDeAiBtn") })}/>`);
  }
  lines.push('        </group>');

  // 各分类 group
  groups.forEach((g) => {
    const groupId = `lingxi_${host}_${g.category}`;
    lines.push(`        <group id="${escapeXml(groupId)}" label="${escapeXml(g.label)}">`);
    g.actions.forEach((act) => {
      const id = `quick.${host}.${act.key}`;
      lines.push(`          <button ${buttonAttrs({ id, label: act.label, size: "normal", iconPath: iconPathForButton(host, qa, id, act, g.category) })}/>`);
    });
    lines.push('        </group>');
  });

  lines.push('      </tab>');
  lines.push('    </tabs>');
  lines.push('  </ribbon>');
  lines.push('</customUI>');
  return lines.join("\n") + "\n";
}

function main() {
  const qa = loadQuickActions();
  const host = readAddonType();
  const xml = buildRibbon(host, qa);
  const callbackJs = buildRibbonCallbackScript(host, qa);
  const target = path.resolve(root, "ribbon.xml");
  fs.writeFileSync(target, xml);
  fs.writeFileSync(generatedRibbonCallbacksPath, callbackJs);
  const groups = qa.getRibbonGroups(host);
  const buttonCount = groups.reduce((sum, g) => sum + g.actions.length, 0);
  console.log(`[gen-ribbon] addonType=${host} → ${groups.length} 组、${buttonCount} 个快捷按钮，写入 ${target}`);
}

if (require.main === module) {
  main();
}

module.exports = {
  actionCallbackName,
  buildRibbon,
  buildRibbonCallbackScript,
  buttonAttrs,
  iconPathForButton,
  imageCallbackName,
  loadQuickActions,
  pngIconPath,
  readAddonType
};
